# Moved to travis-ci.com from travis-ci.org
language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
env:
  global:
    secure: hW6cb9rGAxu8hB3zOyq9KXgUAIjZ7sAA3DoR/Hw4La6kFT2fIVLu+/7u3ThY8Vg02x1TAe1lklAvo72vGDA/vXVJ9EJ+ovV2vfp8QAGqTi8NGUqwANDLt+DFHX7LvRJ/Bq5PIRx1lH53S+lk0aYOvtLfVaGSnKJDhxTuC0PoW80roXV7ee9foeU7vFCXxTPnLBJ8CC4UpAJBNo9InG/pf4UY3UVywIH9CI1Bp5k2fD9eAn00uehj7w48dasImR3SvxBlO8uBKUPOCdkk+eTGNnazMP7DuahZMk95Zon42DkZ5cN/h7EUH6CUqYvxRX1R+vLHcZTbxZIRwprcyuQfT5a5Jal8Zvi+7HacnqtspKTzcE2r452V19mCD52GjpwVcO+WxlPkdpZOMJFy+h9C/L03xnpfIeSWen3iwE/v3q6xdbzZuV+XidpDi4ch1nHhEd2ZbWq7SmshSOpevYPFWP8CMMJGr10EV1S2mBOoPvfnRK6p+uil9XmsOHnN+Na84YK1wrEByGlqL3IVppFlfybVyorHkFIu5JmXAILOGzWhM+7ymRlUwcbTPO1gXwxh4yOLSPlHcb58p8heFNtFRl5Gmx30gGPdXPjzScTbDqWCrjegg1uYTqVZ2d5CXEkjql2CqNUdTmLupulEXI/phr1h2/S5z+Upg82k2ceGXwQ=
